name       : zuki-themes
version    : 3.30.1
release    : 6
source     :
    - https://github.com/lassekongo83/zuki-themes/archive/v3.30-1.tar.gz : 961611bf8f3e3afc64a9707dcd6bbde4daed3f175d6f1689afe9ddbff56b20e2
license    : GPL-3.0
component  : desktop.theme
summary    : Simple and clean grey themes for GTK+ based desktops
description: |
    Simple and clean grey themes for GTK+ based desktops
install    : |
    install -d -m 00755 $installdir/usr/share/themes
    mv Zukitwo Zukitre Zuki-shell $installdir/usr/share/themes
