name       : zuki-themes
version    : '3.20'
release    : 2
source     :
    - https://github.com/lassekongo83/zuki-themes/archive/v3.20-1.tar.gz : b1c6c60d5bc47085054c52b75c8f05b97a7abc33f922ff3af16ecf41efb03437
license    : GPL-3.0
component  : desktop.theme
summary    : Simple and clean grey themes for GTK+ based desktops
description: |
    Simple and clean grey themes for GTK+ based desktops
install    : |
    install -dm0644 $installdir/usr/share/themes
    mv Zukitwo Zukitre $installdir/usr/share/themes
