name       : zuki-themes
version    : 3.28.3
release    : 5
source     :
    - https://github.com/lassekongo83/zuki-themes/archive/v3.28-3.tar.gz : 3b598986e222f9d5ad0cfd2056036e0eeaad39c86c2a8eeaa98bd2eb8e8d983d
license    : GPL-3.0
component  : desktop.theme
summary    : Simple and clean grey themes for GTK+ based desktops
description: |
    Simple and clean grey themes for GTK+ based desktops
install    : |
    install -d -m 00755 $installdir/usr/share/themes
    mv Zukitwo Zukitre Zuki-shell $installdir/usr/share/themes
