name       : zuki-themes
version    : 3.32.4
release    : 8
source     :
    - https://github.com/lassekongo83/zuki-themes/archive/v3.32-4.tar.gz : 77d1d4e6288fb4b8487f5ec88913a9338f262a21bbfd572604932462a8610ce7
license    : GPL-3.0
component  : desktop.theme
summary    : Simple and clean grey themes for GTK+ based desktops
description: |
    Simple and clean grey themes for GTK+ based desktops
builddeps  :
    - sassc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
