name       : zuki-themes
version    : 3.32.1
release    : 7
source     :
    - https://github.com/lassekongo83/zuki-themes/archive/v3.32-1.tar.gz : 338c2c3e5c8a848ffd1c8b234fa31d2e95ae786305951fc08b7bf9b5fb26dcfc
license    : GPL-3.0
component  : desktop.theme
summary    : Simple and clean grey themes for GTK+ based desktops
description: |
    Simple and clean grey themes for GTK+ based desktops
install    : |
    install -d -m 00755 $installdir/usr/share/themes
    mv Zukitwo Zukitre Zuki-shell $installdir/usr/share/themes
