name       : zuki-themes
version    : 3.34.1
release    : 9
source     :
    - https://github.com/lassekongo83/zuki-themes/archive/v3.34-1.tar.gz : 860ec882b73d961af0cce4556d7dfce9013891cd8ba8e13fe8a0f928b4cf3a7d
license    : GPL-2.0-or-later
component  : desktop.theme
summary    : Simple and clean grey themes for GTK+ based desktops
description: |
    Simple and clean grey themes for GTK+ based desktops
builddeps  :
    - sassc
rundesps   :
    - gtk-engines
    - gtk2-engine-murrine
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/themes/*/xfwm4
