name       : zuki-themes
version    : 3.36.3
release    : 11
source     :
    - https://github.com/lassekongo83/zuki-themes/archive/v3.36-3.tar.gz : aca7a05e1e8ad334ce5fba0c821fad2bcd4dd41b95d1ba3b059aa1762561409b
homepage   : https://github.com/lassekongo83/zuki-themes
license    : GPL-2.0-or-later
component  : desktop.theme
summary    : Simple and clean grey themes for GTK+ based desktops
description: |
    Simple and clean grey themes for GTK+ based desktops
builddeps  :
    - sassc
rundesps   :
    - gtk-engines
    - gtk2-engine-murrine
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/themes/*/xfwm4
