name       : zuki-themes
version    : '3.22'
release    : 3
source     :
    - https://github.com/lassekongo83/zuki-themes/archive/v3.22-1.tar.gz : 4dff864c7abe51cf2d882aab32c8a8e7f5fb5ed77762f5e00932b32b85b9cc47
license    : GPL-3.0
component  : desktop.theme
summary    : Simple and clean grey themes for GTK+ based desktops
description: |
    Simple and clean grey themes for GTK+ based desktops
install    : |
    install -d -m 00755 $installdir/usr/share/themes
    mv Zukitwo Zukitre $installdir/usr/share/themes
