name       : zuki-themes
version    : '4.0'
release    : 13
source     :
    - https://github.com/lassekongo83/zuki-themes/archive/v4.0.tar.gz : 262be2169a82f437262b044567e135527c247406950c4806ba50d85f01ebb460
homepage   : https://github.com/lassekongo83/zuki-themes
license    : GPL-2.0-or-later
component  : desktop.theme
summary    : Simple and clean grey themes for GTK+ based desktops
description: |
    Simple and clean grey themes for GTK+ based desktops
builddeps  :
    - sassc
rundesps   :
    - gtk-engines
    - gtk2-engine-murrine
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/themes/*/xfwm4
