name       : zuki-themes
version    : 3.34.2
release    : 10
source     :
    - https://github.com/lassekongo83/zuki-themes/archive/v3.34-2.tar.gz : a43e9e8950b14311d4d8e54fb6b7c330f3d93990cda3bdd9395d7fcbe8a657dc
homepage   : https://github.com/lassekongo83/zuki-themes
license    : GPL-2.0-or-later
component  : desktop.theme
summary    : Simple and clean grey themes for GTK+ based desktops
description: |
    Simple and clean grey themes for GTK+ based desktops
builddeps  :
    - sassc
rundesps   :
    - gtk-engines
    - gtk2-engine-murrine
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/themes/*/xfwm4
