name       : zuki-themes
version    : 3.38.1
release    : 12
source     :
    - https://github.com/lassekongo83/zuki-themes/archive/v3.38-1.tar.gz : a3923b169cd550fffc437cf5f098b8a1f84ab0cad5c07b1b6fa25b0e80439893
homepage   : https://github.com/lassekongo83/zuki-themes
license    : GPL-2.0-or-later
component  : desktop.theme
summary    : Simple and clean grey themes for GTK+ based desktops
description: |
    Simple and clean grey themes for GTK+ based desktops
builddeps  :
    - sassc
rundesps   :
    - gtk-engines
    - gtk2-engine-murrine
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/themes/*/xfwm4
